# Generated by Django 4.0.3 on 2022-06-03 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_user_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
